/* Promo Hero: source registry. Every legal claim behind a flag is tracked here with its citation,
 * verification status, and the date it was last checked against a primary source.
 * status: "verified" (matches primary text), "partial" (some of the claim confirmed, see notes),
 * "incorrect" (primary source contradicts or narrows the claim), "unchecked" (not yet compared to a source).
 * reviewedBy stays null until an attorney signs off. Nothing here is legal advice. */
(function () {
  const NS = (globalThis.PromoHero = globalThis.PromoHero || {});

  const AUDIT_DATE = '2026-09-27';
  const rec = (r) => Object.assign({ reviewedBy: null, verifiedOn: null, cite: '', url: '', excerpt: '', notes: '' }, r);

  const SOURCES = [
    rec({
      id: 'NY_GBL_369E', flagIds: ['REG_NY', 'NY_DEADLINE'], status: 'verified', verifiedOn: AUDIT_DATE,
      claim: 'NY: total announced prize value in excess of $5,000 requires registration at least 30 days before start, and a bond equal to total prizes.',
      cite: 'N.Y. Gen. Bus. Law 369-e(1), (4)',
      url: 'https://www.nysenate.gov/legislation/laws/GBS/369-E',
      excerpt: 'total announced value of the prizes offered is in excess of five thousand dollars; at least thirty days prior to the commencement of such game, contest or promotion; bond ... in an amount equal to the total value of all prizes offered',
      notes: 'Statute covers promotions "in connection with the promotion, advertising or sale of consumer products", which the flag text does not mention. The flag says "bond or trust"; only the bond was confirmed here. Fetched through a summarizing tool, so a human should re-read the statute.',
    }),
    rec({
      id: 'FL_849_094', flagIds: ['REG_FL', 'FL_DEADLINE'], status: 'verified', verifiedOn: AUDIT_DATE,
      claim: 'FL: total announced prize value greater than $5,000 requires registration at least 7 days before start, and a trust account or surety bond for total prizes.',
      cite: 'Fla. Stat. 849.094 (subs. (4) and (10))',
      url: 'http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0800-0899/0849/Sections/0849.094.html',
      excerpt: 'the total announced value of the prizes offered is greater than $5,000; at least 7 days before the commencement of the game promotion; trust account or surety bond',
      notes: 'Statute defines a game promotion as one "in connection with and incidental to the sale of consumer products or services" and lists exemptions in subsection (10) (for example nonprofits). The flag only says "some exemptions exist". Fetched through a summarizing tool, so a human should re-read the statute.',
    }),
    rec({
      id: 'RI_11_50_1', flagIds: ['REG_RI'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'RI: chance promotions by a retail establishment with total announced prizes over $500 must file with the Secretary of State ($150 fee, misdemeanor if not filed).',
      cite: 'R.I. Gen. Laws 11-50-1 (and posting duty in 11-50-2)',
      url: 'https://webserver.rilegislature.gov/Statutes/TITLE11/11-50/11-50-1.htm',
      excerpt: 'total announced value of the prizes offered to the general public is in excess of five hundred dollars ($500); file with the secretary of state; $150; Failure to file a statement shall be a misdemeanor',
      notes: 'Confirmed 2026-09-28. The statute wording ("a retail establishment offers the opportunity to receive gifts, prizes, or gratuities, as determined by chance, in order to promote its retail business") was quoted again from the legislature page and read raw from the Department of State Form 660 instructions. Those instructions also say all games offering over $500 in prizes must register, including games offered to Rhode Island residents from other states, and that a winners list must be kept for at least one year. The engine follows that broader agency position: any chance-based promotion over $500 with RI not excluded. The agency note is guidance, not statute text, so counsel should decide whether a non-retail sponsor is truly covered. No filing deadline appears in the statute.',
    }),
    rec({
      id: 'META_PAGES', flagIds: ['FB_RULES'], status: 'partial', verifiedOn: AUDIT_DATE,
      claim: 'Facebook prohibits requiring sharing or tagging as an entry method.',
      cite: 'Meta Pages, Groups and Events Policies, Promotions',
      url: 'https://www.facebook.com/policies_center/pages_groups_events',
      excerpt: 'Your promotion must not require or incentivize participants to share, repost, tag others, or in any other way publicize your promotion.',
      notes: 'Current wording is broader than the flag ("on personal timelines"): it also covers reposting and incentivizing. No last-updated date was shown. Update the flag text.',
    }),
    rec({
      id: 'TCPA_64_1200', flagIds: ['TCPA'], status: 'partial', verifiedOn: AUDIT_DATE,
      claim: 'Marketing texts need prior express written consent, separate from entry.',
      cite: '47 C.F.R. 64.1200(a)(2), (a)(10), (f)',
      url: 'https://www.law.cornell.edu/cfr/text/47/64.1200',
      excerpt: 'prior express written consent means an agreement, in writing, bearing the signature of the person called ... not required to sign the agreement ... as a condition of purchasing any property, goods, or services',
      notes: 'Rule applies to calls or texts using an autodialer or prerecorded voice; state telemarketing laws were not checked. The rule bars consent as a condition of purchase; extending that to "condition of entry" is an inference. Revocation must be honored within 10 business days.',
    }),
    rec({
      id: 'IRS_1099_MISC', flagIds: ['TAX'], status: 'partial', verifiedOn: AUDIT_DATE,
      claim: 'Winners owe tax; sponsor may need forms and must report prizes above IRS thresholds.',
      cite: 'IRS Instructions for Forms 1099-MISC and 1099-NEC; Pub. L. 119-21',
      url: 'https://www.irs.gov/instructions/i1099mec',
      excerpt: 'Enter other income of $2,000 or more required to be reported on Form 1099-MISC',
      notes: 'The flag wording is generic and safe. The instructions page reported a $2,000 threshold, but the summarizer also reported a revision date later than today, and the IRS 1099-MISC overview page still showed $600. Treat the threshold as unresolved until read directly.',
    }),
    rec({
      id: 'COPPA_312_5', flagIds: ['COPPA'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Collecting personal information from children under 13 requires verifiable parental consent.',
      cite: '16 C.F.R. 312.5(a)(1)',
      url: 'https://www.law.cornell.edu/cfr/text/16/312.5',
      excerpt: 'An operator is required to obtain verifiable parental consent before any collection, use, or disclosure of personal information from children',
      notes: 'The under-13 definition was confirmed in 16 CFR 312.2: "Child means an individual under the age of 13." Both sections were read through a summarizing fetch tool.',
    }),
    rec({
      id: 'NJ_PL2025_C128', flagIds: ['NJ_PAID'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'NJ: a sweepstakes a person in New Jersey can enter by paying or proffering something of value is unlawful gambling unless a free entry method exists and other listed conditions are met.',
      cite: 'P.L. 2025, c.128 (C.52:17B-139.14 to 139.26), sections 2 and 3',
      url: 'https://pub.njleg.state.nj.us/Bills/2024/AL25/128_.PDF',
      excerpt: 'there exists a method of entry to participate in the sweepstakes at no cost to the participant',
      notes: 'Text read directly from the enacted PDF (approved August 15, 2025, effective immediately). The definition covers a sweepstakes "whether played online or in person", so it is not limited to online sweepstakes casinos. Civil penalties are up to $100,000 for a first offense and $250,000 for later ones, each day a separate offense, enforced by the Division of Consumer Affairs. How the $20 ancillary-purchase limit applies to purchase-linked promotions is an interpretation for counsel.',
    }),
    rec({
      id: 'AZ_13_3311', flagIds: ['AZ_CONTEST'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'AZ: amusement gambling intellectual contests must register with the Attorney General, with a sworn statement that no increment was added to the product price.',
      cite: 'A.R.S. 13-3311',
      url: 'https://www.azleg.gov/ars/13/03311.htm',
      excerpt: 'Before any person conducts an amusement gambling intellectual contest or event ... the person shall register with the attorney general\'s office.',
      notes: 'The definition of an amusement gambling intellectual contest (13-3301(1)(d)(iii)) was not read, so which contests qualify is unconfirmed. The flag fires for judged contests tied to a purchase.',
    }),
    rec({
      id: 'HI_481B_1_6', flagIds: ['HI_REALTY'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'HI: a real property prize requires a bond of at least $10,000 filed with the director of commerce and consumer affairs.',
      cite: 'Haw. Rev. Stat. 481B-1.6(e)',
      url: 'https://codes.findlaw.com/hi/division-2-business/hi-rev-st-sect-481b-1-6/',
      excerpt: 'not less than $10,000',
      notes: 'Read through a summarizing fetch tool; a person should re-read the subsection.',
    }),
    rec({
      id: 'CT_42_301', flagIds: ['CT_REVIEW'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Connecticut restricts a sweepstakes or promotional drawing not related to the bona fide sale of goods, services or property, or that uses a simulated gambling device; grocery chains of five or more establishments have an exception.',
      cite: 'Conn. Gen. Stat. 42-301',
      url: 'https://codes.findlaw.com/ct/title-42-business-selling-trading-and-collection-practices/ct-gen-st-sect-42-301/',
      excerpt: 'not related to the bona fide sale of goods, services or property',
      notes: 'Read through a summarizing fetch tool. Whether the two conditions are alternatives or combined is unresolved, so the flag states the text and marks the question for attorney review without taking a side. The Connecticut regulation 42-295-1 (deceptive prize language) and the Department of Consumer Protection page contain no registration duty.',
    }),
    rec({
      id: 'MA_940_CMR', flagIds: ['MA_REVIEW'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Massachusetts bars soliciting or accepting payment for a chance to win a prize and transactions where a gambling purpose predominates over the bona fide sale; prize advertising must identify the prize, its value and conditions.',
      cite: '940 CMR 30.04; 940 CMR 6.08',
      url: 'https://www.law.cornell.edu/regulations/massachusetts/940-CMR-30-04',
      excerpt: 'a gambling purpose predominates over the bona fide sale of bona fide goods or services',
      notes: 'Both sections read through a summarizing tool. How the predominance test applies to a purchase-linked promotion is a legal judgment and is marked for attorney review.',
    }),
    rec({
      id: 'GA_16_12_20', flagIds: ['GA_REVIEW'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Georgia defines a lottery as prizes distributed by chance among persons who have paid or promised consideration and lists exclusions, including promotional giveaways and no-purchase giveaways.',
      cite: 'O.C.G.A. 16-12-20',
      url: 'https://codes.findlaw.com/ga/title-16-crimes-and-offenses/ga-code-sect-16-12-20/',
      excerpt: 'any scheme or procedure whereby one or more prizes are distributed by chance among persons who have paid or promised consideration for a chance to win such prize',
      notes: 'The definition is verified. The exact subsections and conditions of each exclusion were not read, so how they apply is marked for attorney review.',
    }),
    rec({
      id: 'ID_VT_FEE_BANS', flagIds: ['ID_VT_FEES'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Idaho and Vermont bar entry fees, purchases and similar obligations for contests, sweepstakes and promotions.',
      cite: 'IDAPA 04.02.01.080; Vt. Consumer Protection Rule CF 109',
      url: 'https://www.law.cornell.edu/regulations/idaho/IDAPA-04.02.01.080',
      excerpt: 'requires any kind of entry fee, service charge, purchase, payments to information providers, or other obligation in order to enter or participate',
      notes: 'Both rules read through a summarizing tool. Idaho\'s rule is stated for "sellers"; how it applies to a given promotion, including a purchase-linked entry with a free route, is marked for attorney review.',
    }),
    rec({
      id: 'LA_KY_PHONE', flagIds: ['LA_KY_REVIEW'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Louisiana requires sponsors that solicit calls for prizes or sweepstakes to give the Attorney General ad scripts and recordings; Kentucky regulates prize offers made by telephone.',
      cite: 'La. R.S. 51:1732; KRS 367.46951, 367.46977',
      url: 'https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=54552',
      excerpt: 'Offering the person called a prize, gift, or anything else of value, if payment of money or other consideration is required in order to receive the prize or gift',
      notes: 'The Kentucky telephone solicitation statutes were read directly from official PDFs. The Louisiana section was seen only in a search result, so its text is unread. Whether a text-message promotion is covered by either is unresolved and marked for attorney review.',
    }),
    rec({
      id: 'PRIZE_NOTICE_STATUTES', flagIds: ['PRIZE_NOTICE'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Many states bar requesting payment before a written prize notice with sponsor identity, retail value, odds and fees, and set prize delivery times.',
      cite: 'Iowa Code 714B.2; N.D.C.C. 53-11-02; Minn. Stat. 325F.755; Tenn. Code 47-18-124; Wis. Stat. 100.171; K.S.A. 50-692; SDCL 37-32; Utah Code 13-28; Wyo. Stat. 40-12-201 to 209',
      url: 'https://www.legis.iowa.gov/docs/code/2023/714B.pdf',
      excerpt: 'A sponsor of a prize shall not require a person to purchase merchandise or pay or donate money as a condition of awarding a prize',
      notes: 'The Iowa, North Dakota, South Dakota, Utah and Wyoming texts were read directly from official PDFs; the others through a summarizing tool. These statutes are aimed at solicitations that invite payment or a sales presentation. Whether they reach an online promotion with a required purchase is unresolved and marked for attorney review.',
    }),
    rec({
      id: 'IG_PROMO_GUIDELINES', flagIds: ['IG_RULES'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Instagram prohibits inaccurate tagging and encouraging users to tag people who are not in the photo.',
      cite: 'Instagram Promotion Guidelines',
      url: 'https://www.facebook.com/help/instagram/179379842258600',
      excerpt: 'You must not inaccurately tag content or encourage users to inaccurately tag content (example: don\'t encourage people to tag themselves in photos if they aren\'t in the photo).',
      notes: 'No date shown on the page. Read through a summarizing fetch tool; platform rules change, so re-check before launch.',
    }),
    rec({
      id: 'LOTTERY_ELEMENTS', flagIds: ['LOTTERY'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'A scheme distributing prizes by chance among people who have paid consideration is an illegal lottery, so a random drawing with a required purchase or fee is an illegal lottery.',
      cite: 'Cal. Penal Code 319 as applied in Cal. AG Op. 02-809; also Ala. Code 13A-12-20, Ga. Code 16-12-20, 21 O.S. 1051, NMSA 30-19-1, 17-A M.R.S. 952',
      url: 'https://oag.ca.gov/system/files/opinions/pdfs/02-809.pdf',
      excerpt: 'A lottery thus has three essential elements: (1) a prize, (2) distributed by chance and (3) the',
      notes: 'The California opinion (text read directly from the official PDF) held that a purchase-linked drawing for a free vacation is an unlawful lottery. The same three elements appear in the other statutes read. The claim "in most states" is consistent with every state statute read but was not counted across all 50.',
    }),
    rec({
      id: 'VOTE_CHANCE', flagIds: ['VOTE_PAY', 'VOTES'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Winners chosen by votes are frequently treated as chance-based, and paid entries or votes can make the promotion an unlawful lottery.',
      cite: 'Cal. Penal Code 319 (lottery elements); Alaska Stat. 11.66.280 and Ala. Code 13A-12-20 ("material degree" of chance)',
      url: 'https://codes.findlaw.com/ak/title-11-criminal-law/ak-st-sect-11-66-280/',
      excerpt: 'in which the outcome depends in a material degree upon an element of chance, notwithstanding that the skill of the contestants may also be a factor',
      notes: 'The lottery elements and the "material degree" test are verified. That public voting counts as chance was supported only by secondary sources and a search summary of an attorney general opinion, so it is unconfirmed. A paid vote is verified as consideration only if the vote outcome is chance.',
    }),
    rec({
      id: 'AMOE_EQUAL', flagIds: ['AMOE_QUALITY'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'The free entry route must give identical odds, be disclosed as prominently as the paid route, and be treated the same.',
      cite: 'Cal. AG Op. 85-901; Tex. AG LO97-008; N.J. P.L. 2025, c.128, section 3(b)(7); Cal. Bus. & Prof. Code 17539.15',
      url: 'https://www.oag.ca.gov/system/files/opinions/pdfs/85-901_0.pdf',
      excerpt: 'where the fact that any such chance is freely available upon request is neither publicly disclosed nor generally known',
      notes: 'California opinion 85-901 (read directly from the PDF) found a scheme to be a lottery when the free chance was not publicly disclosed. The Texas letter opinion (via summarizer) says any character of favoritism toward paying customers can make it a lottery. New Jersey requires identical odds for free and paid entries. California 17539.15 bars disadvantaging entries without a purchase. Same deadlines and no extra hurdles are good practice, not separately sourced.',
    }),
    rec({
      id: 'EFFORT_CONSIDERATION', flagIds: ['EFFORT'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Requiring significant time or effort to enter is treated as consideration in some states, so offer a free, simple alternative.',
      cite: 'RCW 9.46.0356; Alaska Stat. 11.66.280; Ala. Code 13A-12-20; BBB National Programs CARU guidance (Sept. 18, 2025)',
      url: 'https://app.leg.wa.gov/rcw/default.aspx?cite=9.46.0356',
      excerpt: 'Visiting a business location, placing or answering a telephone call, completing an entry form or customer survey',
      notes: 'No statute, regulation or attorney general opinion read says substantial effort is consideration. Washington says visiting a business, calling, an entry form or survey, or a stamped self-addressed envelope is not consideration. Alaska, Alabama and Maine define "something of value" as money, property or a promise to transfer them, which does not obviously include effort. CARU, the children\'s advertising self-regulator, says promotions cannot ask entrants to spend excessive time creating content, engaging on social media or completing in-game tasks. The tool treats effort as consideration as a conservative default, which is a policy choice for counsel, not a sourced rule.',
    }),
    rec({
      id: 'FIRSTCOME_CHANCE', flagIds: ['FIRSTCOME_PAY'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'A speed-based contest can be treated as one of chance when chance materially affects the outcome, and chance plus payment is a lottery.',
      cite: 'NMSA 30-19-1; Alaska Stat. 11.66.280; Ala. Code 13A-12-20',
      url: 'https://codes.findlaw.com/nm/chapter-30-criminal-offenses/nm-st-sect-30-19-1/',
      excerpt: 'offers of purses, prizes or premiums to the actual contestants in any bona fide contest for the determination of skill, speed, strength or endurance',
      notes: 'Verified: New Mexico excludes prizes for bona fide contests of skill, speed, strength or endurance from its definition of a bet. Alaska and Alabama define a contest of chance as one where the outcome depends in a material degree on chance even if skill also matters. That network lag or random tie-breaks make a first-come promotion one of chance is an inference from those texts; no statute, opinion or case on latency or ties was found.',
    }),
    rec({
      id: 'SKILL_FEES', flagIds: ['FEE_SKILL'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Some states restrict or regulate paid skill contests.',
      cite: 'IDAPA 04.02.01.080; Vt. Consumer Protection Rule CF 109; A.R.S. 13-3311',
      url: 'https://www.law.cornell.edu/regulations/idaho/IDAPA-04.02.01.080',
      excerpt: 'requires any kind of entry fee, service charge, purchase, payments to information providers, or other obligation in order to enter or participate',
      notes: 'Idaho bars an entry fee or purchase for any game of chance, contest, sweepstakes or promotion. Vermont CF 109 bars solicitations that require an entry fee or purchase to enter. Arizona requires registration for certain intellectual contests. See states.js and states2.js.',
    }),
    rec({
      id: 'SKILL_CRITERIA', flagIds: ['CRITERIA'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'A skill contest needs defined, objective criteria; without them it may be treated as a game of chance.',
      cite: 'Alaska Stat. 11.66.280; Ala. Code 13A-12-20',
      url: 'https://codes.findlaw.com/ak/title-11-criminal-law/ak-st-sect-11-66-280/',
      excerpt: 'in which the outcome depends in a material degree upon an element of chance, notwithstanding that the skill of the contestants may also be a factor',
      notes: 'Verified only that skill can coexist with chance and still be a contest of chance where chance is material. The need for weighted, objective criteria is good practice and was not sourced to a statute.',
    }),
    rec({
      id: 'WINNER_FEES', flagIds: ['WINNER_PAYS'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Requiring winners to pay to claim a prize is deceptive under FTC and state law and can turn a lawful promotion into a lottery.',
      cite: 'Nev. Rev. Stat. 598.092(7); Iowa Code 714B.2; N.D.C.C. 53-11-02; 16 C.F.R. 310.3(a)(1)(iv), 310.4(d)(4)',
      url: 'https://www.leg.state.nv.us/nrs/nrs-598.html',
      excerpt: 'that as a condition of receiving the prize he or she must purchase or lease goods or services',
      notes: 'State statutes verified: Nevada makes it a deceptive practice to notify someone they won and require a purchase or lease; Iowa and North Dakota bar payment as a condition of a prize unless a written prize notice is delivered first. The FTC Telemarketing Sales Rule requires disclosure of the odds and that no purchase or payment is required in a prize promotion; it is not a flat ban on winner fees, so the FTC part of the flag wording is overstated.',
    }),
    rec({
      id: 'AGE_OF_MAJORITY', flagIds: ['AGE_MAJORITY'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'The age of majority is 19 in Alabama and Nebraska, so an 18-and-up promotion reaches minors there.',
      cite: 'Ala. Code 26-1-1; Neb. Rev. Stat. 43-2101',
      url: 'https://nebraskalegislature.gov/laws/statutes.php?statute=43-2101',
      excerpt: 'All persons under nineteen years of age are declared to be minors',
      notes: 'Alabama and Nebraska are verified at 19. Mississippi is commonly cited at 21 but the statute page could not be read, so it is not included in the flag. Other states were not surveyed.',
    }),
    rec({
      id: 'MINORS_PRIVACY', flagIds: ['MINORS', 'KIDS'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Minors need parent or guardian permission and prizes go to the parent; state privacy laws add duties for teen data; children\'s advertising standards apply to promotions aimed at children.',
      cite: '16 C.F.R. 312.2 (child means under 13); Cal. Civ. Code 1798.120(c)',
      url: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1798.120',
      excerpt: 'has actual knowledge that the consumer is less than 16 years of age',
      notes: 'COPPA defines a child as under 13 (verified). California requires opt-in before selling or sharing data of consumers under 16 (parent for under 13, the consumer for 13 to 15). CARU (BBB National Programs blog, September 18, 2025) says to obtain verifiable parental consent before collecting personal information from children under 13 and that promotions may not ask children to spend excessive time or effort; that is guidance on the CARU guidelines, not the guidelines text itself. Parent permission for entry and prize delivery to a parent are drafting practice tied to the age of majority (19 in Alabama and Nebraska).',
    }),
    rec({
      id: 'ALCOHOL_AGE_21', flagIds: ['ALCOHOL_AGE', 'ALCOHOL'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Alcohol promotions must be limited to people of legal drinking age (21 in the U.S.), and federal and state alcohol laws limit inducements, purchase-linked promotions and shipping.',
      cite: '23 U.S.C. 158; Md. COMAR 14.23.04.08; 28-A M.R.S. 708-A',
      url: 'https://www.law.cornell.edu/uscode/text/23/158',
      excerpt: 'purchase or public possession in such State of any alcoholic beverage by a person who is less than twenty-one years of age is lawful',
      notes: 'The 21 age is verified as the condition Congress sets on state highway funding, not as a direct advertising rule. State alcohol promotion rules were verified for Maryland (14-day approval, alternative entry) and Maine (in-pack sweepstakes not contingent on purchase). Federal law was read: 27 CFR 6.21 bars industry members from inducing retailers to buy their products (it does not address consumer sweepstakes), and 27 U.S.C. 122 prohibits shipping liquor into a state where it would violate that state\'s law. So federal law does not directly regulate a consumer sweepstakes prize, and the flag text was narrowed to say so.',
    }),
    rec({
      id: 'TOBACCO_GIFTS', flagIds: ['TOBACCO'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'FDA and state rules restrict giveaways and promotions for tobacco and vapes, and platforms ban most of them.',
      cite: '21 C.F.R. 1140.34(b)',
      url: 'https://www.law.cornell.edu/cfr/text/21/1140.34',
      excerpt: 'any gift or item (other than cigarettes or smokeless tobacco) to any person purchasing cigarettes or smokeless tobacco in consideration of the purchase thereof',
      notes: 'Verified for cigarettes and smokeless tobacco: gifts in consideration of a purchase are prohibited. 21 CFR 1140.16 has no gift or contest provision. Part 1140 applies to "cigarettes, smokeless tobacco, and covered tobacco products" (21 CFR 1140.1), but the gift ban in 1140.34(b) names cigarettes and smokeless tobacco, so whether it reaches vapes is unresolved. Meta\'s policy 12 requires compliance with laws on age-restricted products but does not name tobacco.',
    }),
    rec({
      id: 'CANNABIS_FEDERAL', flagIds: ['CANNABIS'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Cannabis remains illegal under federal law, state rules often ban giveaways, and every major social platform prohibits these promotions.',
      cite: '21 U.S.C. 812(c)(10) and (c)(17); 7 U.S.C. 1639o',
      url: 'https://www.law.cornell.edu/uscode/text/21/812',
      excerpt: 'Tetrahydrocannabinols, except for tetrahydrocannabinols in hemp (as defined under section 1639o of title 7).',
      notes: 'Marihuana is listed in Schedule I (verified). Hemp with no more than 0.3 percent delta-9 THC is defined separately and excepted, so hemp-derived CBD is not federally Schedule I. The flag lumped "Cannabis or CBD" together and called it federally illegal, which overstated CBD; it was reworded. Meta\'s Pages, Groups and Events policy 12 says pages must not promote illegal products and must comply with laws on age-restricted substances, which supports "restrict or prohibit" but not "every platform". State giveaway rules are unverified.',
    }),
    rec({
      id: 'FIREARMS_TRANSFER', flagIds: ['FIREARMS'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Awarding a firearm requires a licensed dealer transfer and background check, and platforms prohibit these promotions.',
      cite: '18 U.S.C. 922(a)(1)(A), (a)(3), (a)(5), (t)(1)',
      url: 'https://www.law.cornell.edu/uscode/text/18/922',
      excerpt: 'contact the national instant criminal background check system established under section 103 of that Act',
      notes: 'Verified: unlicensed persons may not deal in firearms as a business, may not transfer a firearm to a resident of another state, and a licensed dealer must run an instant background check before transferring a firearm to a non-licensee. A purely in-state private transfer is not covered by these provisions, so "requires" is a simplification and the flag was reworded. Meta policy 12 requires compliance with applicable laws but does not name firearms in the promotions policy.',
    }),
    rec({
      id: 'FINANCIAL_ADS', flagIds: ['FINANCIAL'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Promotions for credit, loans or investments trigger extra advertising and inducement rules.',
      cite: '12 C.F.R. 1026.24(d)',
      url: 'https://www.law.cornell.edu/cfr/text/12/1026.24',
      excerpt: 'If any of the following terms is set forth in an advertisement, the advertisement shall meet the requirements of paragraph (d)(2) of this section.',
      notes: 'Verified for consumer credit advertising (triggering terms require additional disclosures). For broker-dealers, FINRA Rule 2210(d)(1) requires communications to be fair and balanced and bars false, exaggerated, unwarranted, promissory or misleading claims (read through a summarizing tool). SEC advertising rules for advisers were not checked.',
    }),
    rec({
      id: 'PHARMA_KICKBACK', flagIds: ['PHARMA'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Giveaways tied to prescription drugs or medical services can implicate anti-kickback, FDA advertising, and state law.',
      cite: '42 U.S.C. 1320a-7b(b)(2); 21 C.F.R. 202.1',
      url: 'https://www.law.cornell.edu/uscode/text/42/1320a-7b',
      excerpt: 'Whoever knowingly and willfully offers or pays any remuneration (including any kickback, bribe, or rebate)',
      notes: 'The federal anti-kickback statute (felony, up to $100,000 and 10 years) and the FDA prescription drug advertising rule (brief summary and fair balance) were verified. State law was not checked.',
    }),
    rec({
      id: 'FTC_ENDORSEMENT', flagIds: ['FTC_DISCLOSE', 'INFLUENCER'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Entrant and influencer posts need a clear disclosure of the connection, such as a hashtag with the word contest or sweepstakes.',
      cite: '16 C.F.R. 255.5; FTC Endorsement Guides Q&A on contests and sweepstakes',
      url: 'https://www.ftc.gov/business-guidance/resources/ftcs-endorsement-guides-what-people-are-asking',
      excerpt: 'Making the word "contest" or "sweepstakes" part of the hashtag (e,g., #XZY_Contest or #XYZ_Sweepstakes) should be enough.',
      notes: '255.5 requires disclosure of material connections, including free or discounted products and monetary payment. The FTC Q&A says a hashtag like #XYZ_Rocks is not enough and that the word contest or sweepstakes in the hashtag should be. The separate FTC Disclosures 101 page (dated November 2019) says #ad is fine but not necessary. Quotes read through a summarizing tool.',
    }),
    rec({
      id: 'MARKETING_CONSENT', flagIds: ['MARKETING_REQUIRED'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Making marketing consent mandatory to enter raises consent-validity risk under state privacy laws and CAN-SPAM practice.',
      cite: 'Cal. Civ. Code 1798.140 (consent); 15 U.S.C. 7704(a)(3); 47 C.F.R. 64.1200(f)',
      url: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1798.140',
      excerpt: 'Acceptance of a general or broad terms of use, or similar document, that contains descriptions of personal information processing along with other, unrelated information, does not constitute consent',
      notes: 'The CCPA definition of consent (freely given, specific, informed, unambiguous; not bundled terms or dark patterns) supports the flag. CAN-SPAM does not require prior consent for commercial email (it is an opt-out law), so the reference to CAN-SPAM practice was not supported and has been removed from the flag text. For texts, the TCPA rule says consent cannot be a condition of purchase.',
    }),
    rec({
      id: 'PRIVACY_NOTICE', flagIds: ['PRIVACY'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Collecting names and contact details generally requires a notice at collection or a posted privacy policy, for example under California law.',
      cite: 'Cal. Bus. & Prof. Code 22575(a); Cal. Civ. Code 1798.100(a), 1798.140',
      url: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=22575',
      excerpt: 'An operator of a commercial Web site or online service that collects personally identifiable information through the Internet about individual consumers residing in California',
      notes: 'CalOPPA requires a posted privacy policy from such operators with no size threshold. The CCPA notice at collection applies only to businesses over its thresholds (for example more than $25,000,000 in annual gross revenue, adjusted for inflation, or 100,000 consumers or households).',
    }),
    rec({
      id: 'CHARITY_COVENTURER', flagIds: ['CHARITY'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Tying a purchase or donation to a charity can trigger commercial co-venturer and charitable solicitation registration and disclosure rules in many states.',
      cite: 'Cal. Gov. Code 12599.2',
      url: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12599.2',
      excerpt: 'represents to the public that the purchase or use of any goods, services, entertainment, or any other thing of value will benefit a charitable organization',
      notes: 'Verified for California: a commercial coventurer avoids registration only by keeping a written contract signed by two officers, transferring funds within 90 days and giving a written accounting; otherwise it must register with the Attorney General ($200 fee). Florida also regulates them: a commercial co-venturer is one who regularly and primarily does business other than soliciting contributions and conducts a charitable sales promotion or sponsor sales promotion (Fla. Stat. 496.404(4)). Two states are verified; "many states" is not quantified. New York Executive Law 174-b covers charitable solicitation, not co-venturers.',
    }),
    rec({
      id: 'TRAVEL_SELLERS', flagIds: ['TRAVEL'], status: 'partial', verifiedOn: '2026-09-28',
      claim: 'Some states regulate sellers of travel, and requiring a sales presentation changes the analysis.',
      cite: 'Cal. Bus. & Prof. Code 17550.1; Fla. Stat. 559.927; RCW 19.138.021',
      url: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=17550.1',
      excerpt: 'in exchange for a fee, commission, or other valuable consideration',
      notes: 'California, Florida and Washington define and regulate sellers of travel (California and Florida require registration under other sections). None of the text read addresses travel given as a prize: California 17550.16 and Florida 559.935 list exemptions and neither includes prizes, premiums or promotions, and Florida defines the term by an exchange for a fee, commission or other valuable consideration. So whether a sponsor awarding a trip is a seller of travel is unresolved, and the sales presentation point is unverified.',
    }),
    rec({
      id: 'ARBITRATION_FAA', flagIds: ['ARBITRATION'], status: 'verified', verifiedOn: '2026-09-28',
      claim: 'Enforceability of arbitration and class waivers varies by state and by how clearly the clause is presented; an opt-out and small-claims carve-out help.',
      cite: '9 U.S.C. 2; AT&T Mobility LLC v. Concepcion, 563 U.S. 333 (2011)',
      url: 'https://www.law.cornell.edu/uscode/text/9/2',
      excerpt: 'save upon such grounds as exist at law or in equity for the revocation of any contract',
      notes: 'The Federal Arbitration Act makes written arbitration agreements valid and enforceable except on general contract defenses. Concepcion held that state rules conditioning enforcement on class procedures are preempted, so class waivers are generally enforceable, while unconscionability and formation defenses still vary by state. The opt-out and small-claims carve-out are drafting choices that reduce that risk.',
    }),
  ];

  /** Flags that state no legal claim (input validation or a prompt to the user). */
  const NO_LEGAL_CLAIM = ['DATES', 'ARV_ZERO', 'PLATFORM_TERMS'];

  NS.SOURCES = SOURCES;
  NS.NO_LEGAL_CLAIM = NO_LEGAL_CLAIM;
  NS.sourcesFor = (flagId) => SOURCES.filter((s) => s.flagIds.includes(flagId));
  if (typeof module !== 'undefined') module.exports = NS;
})();
